branch-defaults:
  dev:
    environment: st-api-dev
  master:
    environment: st-api-prod
environment-defaults:
  st-api-prod:
    branch: null
    repository: null
global:
  application_name: st.api
  branch: null
  default_ec2_keyname: StudenTaskAPI
  default_platform: Node.js
  default_region: eu-central-1
  profile: eb-cli
  repository: null
  sc: git
